name: MineSweeperPE
version: 0.4.lpk
api: 4.0.0
src-namespace-prefix: NgLamVN\minesweeper
main: NgLamVN\minesweeper\MineSweeper
description: "A plugin that allow you to play MineSweeper in your Minecraft BE server :3"
authors: [NgLamVN, JINODK, ThinkerS]

permissions:
  mspe.command.start:
    default: true
  mspe.command.stop:
    default: true
  mspe.command.debug:
    default: op
